export const ANALYZE_REPOSITORY = 'ANALYZE_REPOSITORY';
export const RECEIVE_DOCKERFILE = 'RECEIVE_DOCKERFILE';
export const RECEIVE_DOCKERCOMPOSE = 'RECEIVE_DOCKERCOMPOSE';
export const ADD_REPOSITORY = 'ADD_REPOSITORY';
