version: '2'

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local
  node_modules:
    driver: local

services:
  db:
    image: postgres:9.5.3
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./tmp:/tmp
    environment:
      POSTGRES_PASSWORD: P4Ssw0rD!

  web: &app
    image: whalesil/whales-frontend:latest
    command: foreman start -f Procfile
    working_dir: /usr/src/app
    volumes:
      - gems:/usr/local/bundle
      - node_modules:/usr/src/app/client/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/code
    stdin_open: true
    tty: true
    ports:
      - 80:5000
      - 3500:3500
    links:
      - db
    environment: &app_environment
      PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      DATABASE_URL: postgres://postgres:P4Ssw0rD!@db:5432/whales_frontend_development
      CURRENT_DIRECTORY: ${PWD}
      API_BASE_URI: whales.herokuapp.com
    env_file:
      - dev.env
